# Generated by Django 4.1.13 on 2024-03-01 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='content',
        ),
        migrations.AlterField(
            model_name='message',
            name='encrypted_content',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
