# Generated by Django 4.1.13 on 2024-03-01 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0003_message_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='private_key',
            field=models.TextField(blank=True, null=True),
        ),
    ]
